[package]
name = "openmpi"
version = "0.0.1"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
build = "build.rs"

[lib]
name = "openmpi"
path = "src/lib.rs"

#[[bin]]
#name = "test-mpi"
#path = "tools/test-mpi.rs"

[dependencies]
libc = "^0.2.*"
